export const SET_LOADING = 'SET_LOADING';
export const SET_TODOS = 'SET_TODOS';
export const GET_TODOS_MUTATION = 'GET_TODOS_MUTATION';
export const ADD_TODO_MUTATION = 'ADD_TODO_MUTATION';
export const REMOVE_TODO_MUTATION = 'REMOVE_TODO_MUTATION';
export const COMPLETE_TODO_MUTATION = 'COMPLETE_TODO_MUTATION';
